Repository EmulatorJS/EmulatorJS, pull requests merged in 2025-04, with the labels that each got.

#989 Add build script
  .github/workflows/latest.yml
  .github/workflows/npm.yml
  .gitignore
  .npmignore
  build.js
  data/cores/.npmignore
  data/cores/README.md
  data/cores/core-README.md
  data/cores/package.json
  package.json
Labels: enhancement

#987 Update localizations
  README.md
  data/localization/README.md
  data/localization/Translate.html
  data/localization/en-US.json
  data/localization/en.json
  data/localization/retroarch.json
Labels: documentation

#992 Enhance toolbar customisation options
  data/src/emulator.js
Labels: enhancement, possible breaking change

#990 Add update script
  .github/workflows/latest.yml
  README.md
  data/src/nipplejs.js
  data/src/socket.io.min.js
  data/version.json
  docs/contributors.json
  docs/contributors.md
  package.json
  update.js
Labels: enhancement
